
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author nec
 */
public class myContactsForm extends javax.swing.JFrame {

    /**
     * Creates new form myContactsForm
     */
    String imagePth = null;
    public myContactsForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelClose = new javax.swing.JLabel();
        jLabelMn = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelUserPic = new javax.swing.JLabel();
        jLabelUsername = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldLname = new javax.swing.JTextField();
        jTextFieldFname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldPhone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxGroup = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabelContactPic = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaAddress = new javax.swing.JTextArea();
        jButtonBrowseImage = new javax.swing.JButton();
        jButtonAddContact = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(46, 204, 113));
        jPanel1.setLayout(null);

        jLabelClose.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose.setText("X");
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelClose);
        jLabelClose.setBounds(887, 20, 16, 29);

        jLabelMn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelMn.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMn.setText("-");
        jLabelMn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMnMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelMn);
        jLabelMn.setBounds(865, 20, 10, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("My Contacts");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(370, 20, 147, 29);

        jLabelUserPic.setBackground(new java.awt.Color(255, 255, 51));
        jLabelUserPic.setMaximumSize(new java.awt.Dimension(50, 50));
        jLabelUserPic.setMinimumSize(new java.awt.Dimension(50, 50));
        jLabelUserPic.setOpaque(true);
        jLabelUserPic.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(jLabelUserPic);
        jLabelUserPic.setBounds(0, 0, 73, 73);

        jLabelUsername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelUsername.setForeground(new java.awt.Color(253, 227, 167));
        jLabelUsername.setText("Username");
        jPanel1.add(jLabelUsername);
        jLabelUsername.setBounds(80, 0, 120, 73);

        jPanel2.setBackground(new java.awt.Color(236, 236, 236));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 248));
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(44, 62, 80));
        jLabel4.setText("Last Name:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 100, 90, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(44, 62, 80));
        jLabel5.setText("Address:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(380, 220, 70, 22);

        jTextFieldLname.setBackground(new java.awt.Color(228, 241, 254));
        jTextFieldLname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldLname.setForeground(new java.awt.Color(68, 108, 179));
        jTextFieldLname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLnameActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldLname);
        jTextFieldLname.setBounds(120, 100, 180, 30);

        jTextFieldFname.setBackground(new java.awt.Color(228, 241, 254));
        jTextFieldFname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldFname.setForeground(new java.awt.Color(68, 108, 179));
        jTextFieldFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFnameActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldFname);
        jTextFieldFname.setBounds(120, 50, 180, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(44, 62, 80));
        jLabel6.setText("Phone:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 150, 90, 22);

        jTextFieldPhone.setBackground(new java.awt.Color(228, 241, 254));
        jTextFieldPhone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldPhone.setForeground(new java.awt.Color(68, 108, 179));
        jTextFieldPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPhoneActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldPhone);
        jTextFieldPhone.setBounds(120, 150, 180, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(44, 62, 80));
        jLabel7.setText("Email:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 200, 90, 22);

        jTextFieldEmail.setBackground(new java.awt.Color(228, 241, 254));
        jTextFieldEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldEmail.setForeground(new java.awt.Color(68, 108, 179));
        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldEmail);
        jTextFieldEmail.setBounds(120, 200, 180, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(44, 62, 80));
        jLabel8.setText("Group:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(20, 250, 90, 22);

        jComboBoxGroup.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxGroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Family", "Friends", "Work" }));
        jPanel2.add(jComboBoxGroup);
        jComboBoxGroup.setBounds(120, 250, 180, 30);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(350, 30, 20, 280);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(44, 62, 80));
        jLabel9.setText("First Name:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(20, 50, 90, 22);

        jLabelContactPic.setBackground(new java.awt.Color(204, 255, 255));
        jLabelContactPic.setOpaque(true);
        jPanel2.add(jLabelContactPic);
        jLabelContactPic.setBounds(510, 50, 150, 150);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(44, 62, 80));
        jLabel11.setText("Profile Picture:");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(380, 50, 120, 22);

        jTextAreaAddress.setBackground(new java.awt.Color(228, 241, 254));
        jTextAreaAddress.setColumns(20);
        jTextAreaAddress.setForeground(new java.awt.Color(68, 108, 179));
        jTextAreaAddress.setRows(5);
        jScrollPane1.setViewportView(jTextAreaAddress);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(510, 220, 260, 100);

        jButtonBrowseImage.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonBrowseImage.setText("Browse");
        jButtonBrowseImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrowseImageActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonBrowseImage);
        jButtonBrowseImage.setBounds(670, 50, 75, 22);

        jButtonAddContact.setBackground(new java.awt.Color(30, 139, 195));
        jButtonAddContact.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonAddContact.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAddContact.setText("Add");
        jButtonAddContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddContactActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonAddContact);
        jButtonAddContact.setBounds(600, 340, 72, 29);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 914, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 914, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelMnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMnMouseClicked
        // TODO add your handling code here:
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jLabelMnMouseClicked

    private void jTextFieldLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLnameActionPerformed

    private void jTextFieldFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFnameActionPerformed

    private void jTextFieldPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPhoneActionPerformed

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jButtonBrowseImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrowseImageActionPerformed
        // TODO add your handling code here:
        Myfunc mf = new Myfunc();
        imagePth = mf.browseImage(jLabelContactPic);
        System.out.println(imagePth);
    }//GEN-LAST:event_jButtonBrowseImageActionPerformed

    private void jButtonAddContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddContactActionPerformed
        // TODO add your handling code here:
        String fname = jTextFieldFname.getText();
        String lname = jTextFieldLname.getText();
        String phone = jTextFieldPhone.getText();
        String address = jTextAreaAddress.getText();
        String email = jTextFieldEmail.getText();
        String groupc = jComboBoxGroup.getSelectedItem().toString();
        byte[] img = null;
        try {
            Path pth = Paths.get(imagePth);
            img = Files.readAllBytes(pth);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(myContactsForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(myContactsForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        contact c = new contact(null, fname, lname, groupc, phone, email, address, img, 0);
        contactQuery cq = new contactQuery();
        cq.insertContact(c);
    }//GEN-LAST:event_jButtonAddContactActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(myContactsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(myContactsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(myContactsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(myContactsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new myContactsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddContact;
    private javax.swing.JButton jButtonBrowseImage;
    private javax.swing.JComboBox<String> jComboBoxGroup;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelContactPic;
    private javax.swing.JLabel jLabelMn;
    public javax.swing.JLabel jLabelUserPic;
    public javax.swing.JLabel jLabelUsername;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextAreaAddress;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldFname;
    private javax.swing.JTextField jTextFieldLname;
    private javax.swing.JTextField jTextFieldPhone;
    // End of variables declaration//GEN-END:variables
}
