
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.JTableHeader;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author nec
 */
public class myContactsForm extends javax.swing.JFrame {

    /**
     * Creates new form myContactsForm
     */
    String imagePth = null;
    public static int currentUserId;
    public myContactsForm() {
        initComponents();
        populateJTable();
        
        jTable1.setShowGrid(true);
        jTable1.setGridColor(Color.YELLOW);
        jTable1.setSelectionBackground(Color.lightGray);
        
        JTableHeader th = jTable1.getTableHeader();
        th.setForeground(Color.BLUE);
        th.setFont(new Font("Tahoma", Font.PLAIN, 14));
        System.out.println(currentUserId + "From Contact");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelClose = new javax.swing.JLabel();
        jLabelMn = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelUserPic = new javax.swing.JLabel();
        jLabelUsername = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldLname = new javax.swing.JTextField();
        jTextFieldFname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldPhone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxGroup = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabelContactPic = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaAddress = new javax.swing.JTextArea();
        jButtonBrowseImage = new javax.swing.JButton();
        jButtonEditContact = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonAddContact1 = new javax.swing.JButton();
        jTextFieldId = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButtonDeleteContact = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(46, 204, 113));
        jPanel1.setLayout(null);

        jLabelClose.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose.setText("X");
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelClose);
        jLabelClose.setBounds(820, 20, 16, 29);

        jLabelMn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelMn.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMn.setText("-");
        jLabelMn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMnMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelMn);
        jLabelMn.setBounds(790, 20, 10, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("My Contacts");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(370, 20, 147, 29);

        jLabelUserPic.setBackground(new java.awt.Color(255, 255, 51));
        jLabelUserPic.setMaximumSize(new java.awt.Dimension(50, 50));
        jLabelUserPic.setMinimumSize(new java.awt.Dimension(50, 50));
        jLabelUserPic.setOpaque(true);
        jLabelUserPic.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(jLabelUserPic);
        jLabelUserPic.setBounds(0, 0, 73, 73);

        jLabelUsername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelUsername.setForeground(new java.awt.Color(253, 227, 167));
        jLabelUsername.setText("Username");
        jPanel1.add(jLabelUsername);
        jLabelUsername.setBounds(80, 0, 120, 73);

        jPanel2.setBackground(new java.awt.Color(236, 236, 236));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 248));
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(44, 62, 80));
        jLabel4.setText("Last Name:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 140, 90, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(44, 62, 80));
        jLabel5.setText("Address:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(430, 170, 70, 22);

        jTextFieldLname.setBackground(new java.awt.Color(228, 241, 254));
        jTextFieldLname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldLname.setForeground(new java.awt.Color(68, 108, 179));
        jTextFieldLname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLnameActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldLname);
        jTextFieldLname.setBounds(120, 140, 180, 30);

        jTextFieldFname.setBackground(new java.awt.Color(228, 241, 254));
        jTextFieldFname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldFname.setForeground(new java.awt.Color(68, 108, 179));
        jTextFieldFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFnameActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldFname);
        jTextFieldFname.setBounds(120, 90, 180, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(44, 62, 80));
        jLabel6.setText("Phone:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 190, 90, 22);

        jTextFieldPhone.setBackground(new java.awt.Color(228, 241, 254));
        jTextFieldPhone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldPhone.setForeground(new java.awt.Color(68, 108, 179));
        jTextFieldPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPhoneActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldPhone);
        jTextFieldPhone.setBounds(120, 190, 180, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(44, 62, 80));
        jLabel7.setText("Email:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 240, 90, 22);

        jTextFieldEmail.setBackground(new java.awt.Color(228, 241, 254));
        jTextFieldEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldEmail.setForeground(new java.awt.Color(68, 108, 179));
        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldEmail);
        jTextFieldEmail.setBounds(120, 240, 180, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(44, 62, 80));
        jLabel8.setText("Group:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(20, 290, 90, 22);

        jComboBoxGroup.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxGroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Family", "Friends", "Work" }));
        jPanel2.add(jComboBoxGroup);
        jComboBoxGroup.setBounds(120, 290, 180, 30);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(350, 30, 20, 280);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(44, 62, 80));
        jLabel9.setText("First Name:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(20, 90, 90, 22);

        jLabelContactPic.setBackground(new java.awt.Color(204, 255, 255));
        jLabelContactPic.setOpaque(true);
        jPanel2.add(jLabelContactPic);
        jLabelContactPic.setBounds(520, 50, 120, 80);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(44, 62, 80));
        jLabel11.setText("Profile Picture:");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(380, 50, 120, 22);

        jTextAreaAddress.setBackground(new java.awt.Color(228, 241, 254));
        jTextAreaAddress.setColumns(20);
        jTextAreaAddress.setForeground(new java.awt.Color(68, 108, 179));
        jTextAreaAddress.setRows(5);
        jScrollPane1.setViewportView(jTextAreaAddress);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(520, 170, 260, 100);

        jButtonBrowseImage.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonBrowseImage.setText("Browse");
        jButtonBrowseImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrowseImageActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonBrowseImage);
        jButtonBrowseImage.setBounds(670, 50, 75, 22);

        jButtonEditContact.setBackground(new java.awt.Color(30, 139, 195));
        jButtonEditContact.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonEditContact.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEditContact.setText("Edit");
        jButtonEditContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditContactActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonEditContact);
        jButtonEditContact.setBounds(620, 290, 72, 29);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(0, 320, 850, 430);

        jButtonAddContact1.setBackground(new java.awt.Color(30, 139, 195));
        jButtonAddContact1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonAddContact1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAddContact1.setText("Add");
        jButtonAddContact1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddContact1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonAddContact1);
        jButtonAddContact1.setBounds(710, 290, 72, 29);

        jTextFieldId.setBackground(new java.awt.Color(228, 241, 254));
        jTextFieldId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldId.setForeground(new java.awt.Color(68, 108, 179));
        jTextFieldId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldId);
        jTextFieldId.setBounds(120, 40, 180, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(44, 62, 80));
        jLabel10.setText("ID:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(20, 40, 90, 22);

        jButtonDeleteContact.setBackground(new java.awt.Color(30, 139, 195));
        jButtonDeleteContact.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonDeleteContact.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDeleteContact.setText("Delete");
        jButtonDeleteContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteContactActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonDeleteContact);
        jButtonDeleteContact.setBounds(522, 290, 80, 29);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void populateJTable() {
        
        contactQuery cq = new contactQuery();
        ArrayList<contact> ctList = cq.contactList(currentUserId);
        String[] colNames = {"Id", "First Name", "Last Name", "Group", "Phone", "Email", "Address", "Image"};
        Object[][] rows = new Object[ctList.size()][8];
        
        for (int i = 0; i < ctList.size(); i++) {
            rows[i][0] = ctList.get(i).getCid();
            rows[i][1] = ctList.get(i).getFname();
            rows[i][2] = ctList.get(i).getLname();
            rows[i][3] = ctList.get(i).getGroupc();
            rows[i][4] = ctList.get(i).getPhone();
            rows[i][5] = ctList.get(i).getEmail();
            rows[i][6] = ctList.get(i).getAddress();
            
            ImageIcon pic = new ImageIcon(new ImageIcon
                                              (ctList.get(i).getPic())
                                              .getImage()
                                              .getScaledInstance(120, 80, Image.SCALE_SMOOTH));
            
            rows[i][7] = pic;
        }
        
        MyModel mmd = new MyModel(rows, colNames);
        jTable1.setModel(mmd);
        jTable1.setRowHeight(80);
        jTable1.getColumnModel().getColumn(7).setPreferredWidth(120);
    }
    
    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelMnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMnMouseClicked
        // TODO add your handling code here:
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jLabelMnMouseClicked

    private void jTextFieldLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLnameActionPerformed

    private void jTextFieldFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFnameActionPerformed

    private void jTextFieldPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPhoneActionPerformed

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jButtonBrowseImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrowseImageActionPerformed
        // TODO add your handling code here:
        Myfunc mf = new Myfunc();
        imagePth = mf.browseImage(jLabelContactPic);
        System.out.println(imagePth);
    }//GEN-LAST:event_jButtonBrowseImageActionPerformed

    private void jButtonEditContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditContactActionPerformed
        // TODO add your handling code here:
        int id = Integer.valueOf(jTextFieldId.getText());
        String fname = jTextFieldFname.getText();
        String lname = jTextFieldLname.getText();
        String phone = jTextFieldPhone.getText();
        String address = jTextAreaAddress.getText();
        String email = jTextFieldEmail.getText();
        String groupc = jComboBoxGroup.getSelectedItem().toString();
        
        //if the user want to update the data and the image
        if (imagePth != null) {
            byte[] img = null;
            try {
                Path pth = Paths.get(imagePth);
                img = Files.readAllBytes(pth);
                
                contact c = new contact(id, fname, lname, groupc, phone, email, address, img, currentUserId);
                contactQuery cq = new contactQuery();
                cq.updateContact(c, true);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(myContactsForm.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(myContactsForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else {
            contact c = new contact(id, fname, lname, groupc, phone, email, address, null, currentUserId);
            contactQuery cq = new contactQuery();
            cq.updateContact(c, false);
        }
        
    }//GEN-LAST:event_jButtonEditContactActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        // display selected JTable row data
        
        // get selected row index
        int rowIndex = jTable1.getSelectedRow();
        jTextFieldFname.setText(jTable1.getValueAt(rowIndex, 1).toString());
        jTextFieldLname.setText(jTable1.getValueAt(rowIndex, 2).toString());
        
        // group phone email address pic
        jComboBoxGroup.setSelectedItem(jTable1.getValueAt(rowIndex, 3));
        jTextFieldPhone.setText(jTable1.getValueAt(rowIndex, 4).toString());
        jTextFieldEmail.setText(jTable1.getValueAt(rowIndex, 5).toString());
        jTextFieldId.setText(jTable1.getValueAt(rowIndex, 0).toString());
        jTextAreaAddress.setText(jTable1.getValueAt(rowIndex, 6).toString());
        
        Image pic = ((ImageIcon)jTable1.getValueAt(rowIndex, 7)).getImage().getScaledInstance(jLabelContactPic.getWidth(), jLabelContactPic.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon img = new ImageIcon(pic);
        
        jLabelContactPic.setIcon(img);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButtonAddContact1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddContact1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAddContact1ActionPerformed

    private void jTextFieldIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdActionPerformed

    private void jButtonDeleteContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteContactActionPerformed
        // TODO add your handling code here:
        int id = Integer.valueOf(jTextFieldId.getText());
        contactQuery cq = new contactQuery();
        cq.deleteContact(id);
    }//GEN-LAST:event_jButtonDeleteContactActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(myContactsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(myContactsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(myContactsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(myContactsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new myContactsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddContact1;
    private javax.swing.JButton jButtonBrowseImage;
    private javax.swing.JButton jButtonDeleteContact;
    private javax.swing.JButton jButtonEditContact;
    private javax.swing.JComboBox<String> jComboBoxGroup;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelContactPic;
    private javax.swing.JLabel jLabelMn;
    public javax.swing.JLabel jLabelUserPic;
    public javax.swing.JLabel jLabelUsername;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextAreaAddress;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldFname;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldLname;
    private javax.swing.JTextField jTextFieldPhone;
    // End of variables declaration//GEN-END:variables
}
